name: Setup Node.js for JavaScript Actions
description: Setup Node.js environment for JavaScript Actions in Alpine containers
runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      run: |
        if test -d /__e && grep -q '^ID=alpine$' /etc/os-release; then
          apk add --no-cache -- docker-cli libstdc++
          docker run --rm --interactive --user 0:0 --volume /:/hostfs --entrypoint /usr/sbin/chroot "$(docker inspect "$(hostname)" --format "{{ .Image }}")" /hostfs /bin/bash -eo pipefail -xs "$(docker inspect "$(hostname)" --format '{{ range.Mounts }}{{ if eq .Destination "/__e" }}{{ .Source }}{{ end }}{{ end }}')" <<'EOF'
        export DOCKER_CONFIG="$(dirname "$(dirname "$(dirname "$1")")")/.docker"
        find "$1" -type f -executable -name 'node' -not -path '*_alpine/*' -print0 | xargs -0 -n 1 -- /bin/bash -xc 'docker run --rm --volume /:/hostfs "docker.io/library/node:$("$1" -e "console.log(process.versions.node)")-alpine" -e "fs.copyFileSync(process.execPath, process.argv[1])" -- "/hostfs$1"' --
        EOF
          sed -i -e 's/^ID=alpine$/ID=linux/' /etc/os-release
        fi
      shell: sh
